import { describeStep, type Locator, type RunView, type StepView } from '@/core/domain';
import type { ExportedReport, IReportExporter } from '@/core/ports';
import { toLocatorCalls, type LocatorCall } from '../browser/locatorCalls';
import { reportFileName } from './reportFileName';
import { containsPattern, textPattern } from './textPattern';

// Every string from a run reaches the generated file through JSON.stringify (CLAUDE.md s4, 8).
const str = (value: string): string => JSON.stringify(value);
// Line comments end at any JS line terminator, including U+2028 and U+2029, so strip them all.
const LINE_TERMINATORS = new RegExp(`[${String.fromCharCode(10, 13, 0x2028, 0x2029)}]`, 'g');
const comment = (text: string): string => text.replace(LINE_TERMINATORS, ' ');
const WHOLE_VALUE_START = String.raw`^\s*`;
const WHOLE_VALUE_END = String.raw`\s*$`;
const regex = (source: string, flags = ''): string =>
  flags ? `new RegExp(${str(source)}, ${str(flags)})` : `new RegExp(${str(source)})`;

function callCode(call: LocatorCall): string {
  switch (call.method) {
    case 'getByRole':
      return call.name === null
        ? `.getByRole(${str(call.role)})`
        : `.getByRole(${str(call.role)}, { name: ${str(call.name)}, exact: ${String(call.exact)} })`;
    case 'filter':
      return `.filter({ hasText: ${str(call.hasText)} })`;
    case 'getByTestId':
      return `.getByTestId(${str(call.testId)})`;
    default:
      return `.${call.method}(${str(call.text)}, { exact: ${String(call.exact)} })`;
  }
}

/** The locator as Playwright code, built from the same call chain the agent ran. */
export function locatorCode(locator: Locator): string {
  return `page${toLocatorCalls(locator)
    .map((call) => callCode(call))
    .join('')}`;
}

function stepCode(step: StepView, start: URL): string {
  // A healed step uses the locator that worked, so the spec runs against the current UI.
  const target = step.result?.healing?.to ?? step.target;
  const loc = target ? locatorCode(target) : 'page';
  const value = step.value ?? '';
  switch (step.action) {
    case 'navigate':
      return `await page.goto(${str(new URL(value, start).href)});`;
    case 'click':
      return `await ${loc}.click();`;
    case 'check':
      return `await ${loc}.check();`;
    case 'fill':
      return `await ${loc}.fill(${str(value)});`;
    case 'select':
      return `await ${loc}.selectOption({ label: ${str(value)} });`;
    case 'press':
      return target
        ? `await ${loc}.press(${str(value)});`
        : `await page.keyboard.press(${str(value)});`;
    case 'assertVisible':
      return `await expect(${loc}.first()).toBeVisible();`;
    case 'assertHidden':
      return `await expect(${loc}.filter({ visible: true })).toHaveCount(0);`;
    case 'assertText':
      return `await expect(${target ? loc + '.first()' : "page.locator('body')"}).toContainText(${regex(textPattern(value), 'i')});`;
    case 'assertUrl':
      return `await expect(page).toHaveURL(${regex(containsPattern(value))});`;
    case 'assertValue':
      return `await expect(${loc}).toHaveValue(${regex(WHOLE_VALUE_START + textPattern(value) + WHOLE_VALUE_END, 'i')});`;
  }
}

/** A runnable Playwright test file the team can keep, generated from the run's plan. */
export class PlaywrightSpecExporter implements IReportExporter {
  readonly format = 'spec';

  export(view: RunView): ExportedReport {
    const start = new URL(view.targetUrl ?? 'about:blank');
    const tests = view.scenarios.map((scenario) => {
      const steps = scenario.steps.map(
        (step) => `    // ${comment(describeStep(step))}\n    ${stepCode(step, start)}`,
      );
      return [`  test(${str(scenario.title)}, async ({ page }) => {`, ...steps, '  });'].join('\n');
    });
    const body = [
      `// Generated by TestPilot from run ${view.runId ?? 'unknown'} against ${comment(view.targetLabel ?? '')}.`,
      '// Run it with: npx playwright test <this file>',
      "import { expect, test } from '@playwright/test';",
      '',
      `test.describe(${str(view.targetLabel ?? 'TestPilot run')}, () => {`,
      tests.join('\n\n'),
      '});',
      '',
    ].join('\n');
    return {
      fileName: reportFileName(view, 'spec.ts'),
      contentType: 'text/plain; charset=utf-8',
      body,
    };
  }
}
